# Generated by Django 4.1.7 on 2023-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=255)),
                ("created_at", models.CharField(max_length=255)),
                ("created_by", models.CharField(max_length=255)),
                ("updated_at", models.CharField(max_length=255)),
            ],
        ),
    ]
